"""
Module 4 -- Environmental Influence Quantification Engine
Schema migration.

Creates additive-only tables to store ML benchmarking results, the
ML-primary / statistics-supporting influence quantification per
(target_metric, variable), and a run-metadata audit table. NO existing
table (mine_master, sampling_records, weather_records, environmental_*,
etc.) is modified, altered, or regenerated by this module, per explicit
instruction. All joins needed for analysis happen in the data assembly
layer at query/run time, never by writing back to source tables.

Tables:

  module4_run_metadata
      One row per Module 4 run. Records what was actually used (real
      XGBoost/LightGBM/SHAP vs. sklearn-native fallbacks), sample sizes
      per target after data-quality filtering, and timestamps -- full
      transparency about environment capabilities, consistent with how
      Module 2's production-only policy and Milestone 5's FastAPI
      limitation were documented.

  model_benchmark_results
      One row per (run_id, target_metric, model_name): cross-validated
      RMSE/MAE/R² (mean + std across folds), and whether this model was
      selected as best for that target.

  environmental_influence_quantification
      One row per (run_id, target_metric, variable_name): the ML-primary
      importance score (SHAP-based, or permutation-importance fallback)
      and rank, PLUS statistical supporting evidence (Pearson r, Spearman
      rho, best-lag correlation, seasonal breakdown), PLUS reconciliation
      against the Module 3 Knowledge Base hypothesis. This is the
      authoritative Module 4 output table that Module 5 (Explainable AI)
      will read from.

      Critically: this table NEVER claims causation. Every row carries a
      mandatory `causation_caveat` field and an `evidence_label` enum
      ('observed_ml_influence' | 'observed_statistical_association') --
      never 'proven_cause'.
"""

import sqlite3


DDL_STATEMENTS = [
    """
    CREATE TABLE IF NOT EXISTS module4_run_metadata (
        id                          INTEGER PRIMARY KEY AUTOINCREMENT,
        run_started_at              TEXT NOT NULL DEFAULT (datetime('now')),
        run_completed_at            TEXT,
        xgboost_available           INTEGER NOT NULL,
        lightgbm_available          INTEGER NOT NULL,
        shap_available              INTEGER NOT NULL,
        xgboost_substitute_used     TEXT,   -- e.g. 'sklearn.GradientBoostingRegressor' or NULL if real xgboost used
        lightgbm_substitute_used    TEXT,   -- e.g. 'sklearn.HistGradientBoostingRegressor' or NULL
        shap_substitute_used        TEXT,   -- e.g. 'sklearn.permutation_importance' or NULL
        total_mapped_mines          INTEGER,
        mines_with_joined_data      INTEGER,
        sample_count_gcv            INTEGER,
        sample_count_moisture       INTEGER,
        sample_count_ash            INTEGER,
        rows_excluded_ash_invalid   INTEGER,
        rows_excluded_moisture_invalid INTEGER,
        rows_excluded_gcv_invalid   INTEGER,
        notes                       TEXT
    );
    """,
    """
    CREATE TABLE IF NOT EXISTS model_benchmark_results (
        id                  INTEGER PRIMARY KEY AUTOINCREMENT,
        run_id              INTEGER NOT NULL,
        target_metric       TEXT NOT NULL,        -- 'gcv' | 'moisture' | 'ash'
        model_name           TEXT NOT NULL,        -- 'linear_regression' | 'random_forest' | 'xgboost' | 'lightgbm'
        model_implementation TEXT NOT NULL,        -- actual class used, e.g. 'sklearn.ensemble.HistGradientBoostingRegressor'
        cv_folds             INTEGER NOT NULL,
        rmse_mean            REAL NOT NULL,
        rmse_std             REAL NOT NULL,
        mae_mean             REAL NOT NULL,
        mae_std              REAL NOT NULL,
        r2_mean              REAL NOT NULL,
        r2_std               REAL NOT NULL,
        is_selected_best      INTEGER NOT NULL DEFAULT 0,
        training_sample_size  INTEGER NOT NULL,
        created_at            TEXT NOT NULL DEFAULT (datetime('now'))
    );
    """,
    "CREATE INDEX IF NOT EXISTS idx_mbr_run_target ON model_benchmark_results(run_id, target_metric);",

    """
    CREATE TABLE IF NOT EXISTS environmental_influence_quantification (
        id                          INTEGER PRIMARY KEY AUTOINCREMENT,
        run_id                      INTEGER NOT NULL,
        target_metric               TEXT NOT NULL,         -- 'gcv' | 'moisture' | 'ash'
        variable_name                TEXT NOT NULL,         -- logical FK -> environmental_knowledge_base.variable_name
        selected_model_name          TEXT NOT NULL,         -- which model produced this importance ranking
        ml_importance_score          REAL NOT NULL,         -- SHAP mean(|value|) or permutation-importance fallback
        ml_importance_rank           INTEGER NOT NULL,      -- 1 = most influential per target_metric, this run
        ml_importance_method         TEXT NOT NULL,         -- 'shap' | 'permutation_importance'
        ml_direction                 TEXT,                  -- 'positive' | 'negative' | 'mixed' (from SHAP sign or partial dependence trend)
        pearson_r                    REAL,
        spearman_rho                 REAL,
        best_lag_days                INTEGER,                -- lag (0-7) at which correlation with target is strongest
        best_lag_correlation         REAL,
        seasonal_breakdown_json      TEXT,                   -- per-season {pre_monsoon, monsoon, post_monsoon, winter} correlation, JSON text
        kb_hypothesis_direction      TEXT,                   -- environmental_variable_influence.influence_direction at time of run
        kb_hypothesis_confidence     TEXT,                   -- environmental_variable_influence.confidence_level at time of run
        agreement_with_kb            TEXT NOT NULL,          -- 'agrees' | 'disagrees' | 'partial' | 'kb_had_no_directional_hypothesis'
        validation_status_assigned   TEXT NOT NULL,          -- 'validated' | 'partially_validated' | 'rejected' | 'inconclusive'
        evidence_label                TEXT NOT NULL,          -- 'observed_ml_influence' | 'observed_statistical_association'
        causation_caveat              TEXT NOT NULL,          -- mandatory plain-language non-causation disclaimer
        created_at                    TEXT NOT NULL DEFAULT (datetime('now'))
    );
    """,
    "CREATE INDEX IF NOT EXISTS idx_eiq_run_target ON environmental_influence_quantification(run_id, target_metric);",
    "CREATE INDEX IF NOT EXISTS idx_eiq_variable ON environmental_influence_quantification(variable_name);",
]


def run_migration(db_path: str) -> None:
    con = sqlite3.connect(db_path)
    try:
        cur = con.cursor()
        for stmt in DDL_STATEMENTS:
            cur.execute(stmt)
        con.commit()
    finally:
        con.close()


def verify_migration(db_path: str) -> dict:
    expected = ["module4_run_metadata", "model_benchmark_results", "environmental_influence_quantification"]
    con = sqlite3.connect(db_path)
    try:
        cur = con.cursor()
        cur.execute("SELECT name FROM sqlite_master WHERE type='table'")
        existing = {r[0] for r in cur.fetchall()}
        report = {}
        for t in expected:
            if t in existing:
                cur.execute(f"SELECT COUNT(*) FROM {t}")
                report[t] = {"exists": True, "row_count": cur.fetchone()[0]}
            else:
                report[t] = {"exists": False, "row_count": None}
        return report
    finally:
        con.close()


if __name__ == "__main__":
    import sys
    db_file = sys.argv[1] if len(sys.argv) > 1 else "coal_eie.db"
    run_migration(db_file)
    report = verify_migration(db_file)
    print("Module 4 schema migration applied to:", db_file)
    for t, info in report.items():
        print(f"  {t:45s} exists={info['exists']!s:5s} rows={info['row_count']}")
