"""
Module 3 -- Environmental Knowledge Base
MILESTONE 2c: Content population -- environmental_variable_influence.

One row per (variable_name, target_metric) where target_metric is one of
'gcv' | 'moisture' | 'ash'. Every row is a GENERIC hypothesis about how a
variable relates to a coal quality metric -- applicable to any mine. No
mine_code, no statistics computed from this platform's own sampling data.

validation_status is set to 'pending' for every row here, by design -- only
the future Influence Quantification Engine (Module 4) is permitted to
change it after testing each hypothesis against real mine-specific
sampling + weather data.

Rationale for GCV/Moisture/Ash relationships used throughout:
  - Coal GCV (gross calorific value) on an as-received basis is reduced by
    higher total moisture, because moisture displaces combustible mass and
    absorbs heat during combustion (latent heat of vaporisation) -- this is
    standard coal chemistry (see ASTM D3302/IS 1350 moisture-correction
    conventions). Most environmental variables therefore act on GCV
    INDIRECTLY, via their direct effect on moisture, rather than directly.
  - Ash content is a function of the mineral matter in the coal itself
    (geological origin, seam, washing/beneficiation), and is generally
    not expected to be directly altered by short-term weather. Any
    weather-ash relationship in this register is flagged low confidence
    and indirect (e.g. via differential erosion/handling effects) unless
    noted otherwise.
"""

import sqlite3

REF_ASTM_MOISTURE = "ASTM D3302/D3173 -- Standard Test Methods for Total Moisture and Moisture in the Analysis Sample of Coal"
REF_SPEIGHT = "Speight, J.G., Handbook of Coal Analysis (2nd ed.) -- coal moisture and quality relationships"
REF_COAL_HANDBOOK = "Osborne, D. (ed.), The Coal Handbook: Towards Cleaner Production, Vol. 1"
REF_CIMFR_WEATHERING = "Central Institute of Mining and Fuel Research (CIMFR) literature on coal stockpile weathering"
REF_PENMAN = "Penman (1948) evaporation theory; FAO Penman-Monteith framework (FAO Irrigation and Drainage Paper 56)"
REF_PSYCHROMETRY = "Psychrometric principles (ASHRAE Handbook - Fundamentals, Psychrometrics chapter)"
REF_WMO_GLOSSARY = "American Meteorological Society, Glossary of Meteorology"
REF_HYDRO_API = "General hydrological antecedent-precipitation-index concepts (conceptual basis only)"

MOISTURE_GCV_MECHANISM = (
    "Higher moisture content reduces as-received GCV because moisture displaces combustible mass and consumes "
    f"latent heat during combustion ({REF_ASTM_MOISTURE}; {REF_SPEIGHT}); this is the standard indirect pathway "
    "by which environmental variables affect GCV."
)

ROWS = [
    dict(variable_name="temperature", target_metric="gcv", relationship_type="indirect",
         influence_direction="positive", influence_strength="medium",
         expected_lag_days_min=0, expected_lag_days_max=2,
         lag_description="Acts via reduced moisture from sustained warm, dry periods; effect builds over 0-2 days.",
         rationale=f"Higher temperature promotes evaporative drying, lowering moisture, which raises as-received GCV. {MOISTURE_GCV_MECHANISM}",
         knowledge_type="established_principle", scientific_references=f"{REF_PSYCHROMETRY}; {REF_ASTM_MOISTURE}",
         confidence_level="medium", confidence_rationale="Drying mechanism is well established; GCV effect is indirect via moisture, so medium rather than high confidence."),
    dict(variable_name="temperature", target_metric="moisture", relationship_type="direct",
         influence_direction="negative", influence_strength="medium",
         expected_lag_days_min=0, expected_lag_days_max=2,
         lag_description="Drying effect accumulates over hours to a couple of days of sustained warmth.",
         rationale="Warmer air increases the evaporative vapour-pressure gradient at exposed coal surfaces, reducing surface moisture, provided humidity is not simultaneously elevated.",
         knowledge_type="established_principle", scientific_references=f"{REF_PSYCHROMETRY}; {REF_PENMAN}",
         confidence_level="medium", confidence_rationale="Established physics, but effect size is context-dependent on simultaneous humidity."),
    dict(variable_name="temperature", target_metric="ash", relationship_type="indirect",
         influence_direction="context_dependent", influence_strength="low",
         expected_lag_days_min=0, expected_lag_days_max=0,
         lag_description="No established direct lag; any effect would be via differential handling, not temperature itself.",
         rationale="Ash is primarily mineral-matter content intrinsic to the coal; temperature has no direct established mechanism affecting ash.",
         knowledge_type="operational_assumption", scientific_references=None,
         confidence_level="low", confidence_rationale="No established physical mechanism links temperature directly to ash content; treated as a hypothesis to test, likely null."),

    dict(variable_name="relative_humidity", target_metric="gcv", relationship_type="indirect",
         influence_direction="negative", influence_strength="medium",
         expected_lag_days_min=0, expected_lag_days_max=2,
         lag_description="Acts via increased moisture retention; builds over 0-2 days of sustained high humidity.",
         rationale=f"High humidity suppresses evaporative drying, raising moisture, which lowers as-received GCV. {MOISTURE_GCV_MECHANISM}",
         knowledge_type="established_principle", scientific_references=f"{REF_PSYCHROMETRY}; {REF_ASTM_MOISTURE}",
         confidence_level="medium", confidence_rationale="Mechanism well established; GCV link is indirect via moisture."),
    dict(variable_name="relative_humidity", target_metric="moisture", relationship_type="direct",
         influence_direction="positive", influence_strength="high",
         expected_lag_days_min=0, expected_lag_days_max=1,
         lag_description="Near-immediate effect on surface moisture retention.",
         rationale="High relative humidity reduces the vapour-pressure gradient available to drive evaporation, directly increasing surface moisture retention.",
         knowledge_type="established_principle", scientific_references=f"{REF_PSYCHROMETRY}",
         confidence_level="high", confidence_rationale="Direct, fundamental atmospheric physics with minimal context-dependence."),
    dict(variable_name="relative_humidity", target_metric="ash", relationship_type="indirect",
         influence_direction="context_dependent", influence_strength="low",
         expected_lag_days_min=0, expected_lag_days_max=0,
         lag_description="No established mechanism/lag.",
         rationale="No established physical mechanism connects ambient humidity to mineral-matter (ash) content of coal.",
         knowledge_type="operational_assumption", scientific_references=None,
         confidence_level="low", confidence_rationale="Speculative; likely null relationship, included for completeness pending statistical testing."),

    dict(variable_name="rainfall", target_metric="gcv", relationship_type="indirect",
         influence_direction="negative", influence_strength="high",
         expected_lag_days_min=0, expected_lag_days_max=3,
         lag_description="Immediate same-day effect on surface moisture, with residual elevated moisture persisting up to ~3 days depending on drying conditions.",
         rationale=f"Rainfall directly raises surface moisture, which lowers as-received GCV. {MOISTURE_GCV_MECHANISM}",
         knowledge_type="established_principle", scientific_references=f"{REF_COAL_HANDBOOK}; {REF_ASTM_MOISTURE}",
         confidence_level="high", confidence_rationale="Direct wetting-to-moisture-to-GCV pathway is one of the most well documented in coal handling practice."),
    dict(variable_name="rainfall", target_metric="moisture", relationship_type="direct",
         influence_direction="positive", influence_strength="high",
         expected_lag_days_min=0, expected_lag_days_max=1,
         lag_description="Same-day to next-day effect; largely immediate.",
         rationale="Precipitation directly wets exposed coal and stockpile surfaces, raising surface and near-surface moisture content.",
         knowledge_type="established_principle", scientific_references=f"{REF_COAL_HANDBOOK}; {REF_CIMFR_WEATHERING}",
         confidence_level="high", confidence_rationale="Direct physical wetting mechanism, minimal ambiguity."),
    dict(variable_name="rainfall", target_metric="ash", relationship_type="indirect",
         influence_direction="context_dependent", influence_strength="low",
         expected_lag_days_min=0, expected_lag_days_max=2,
         lag_description="If any effect exists, it would manifest via differential fines washing/segregation, not immediately.",
         rationale="Heavy rainfall could in principle cause differential movement of fines vs. coarse material in a stockpile, marginally altering sampled ash, but this is not a well-documented primary mechanism.",
         knowledge_type="operational_assumption", scientific_references=f"{REF_COAL_HANDBOOK}",
         confidence_level="low", confidence_rationale="Plausible secondary mechanism, not well documented; flagged for statistical testing rather than assumed."),

    dict(variable_name="dew_point", target_metric="gcv", relationship_type="indirect",
         influence_direction="negative", influence_strength="low",
         expected_lag_days_min=0, expected_lag_days_max=1,
         lag_description="Acts via condensation-driven moisture gain, typically overnight.",
         rationale=f"A dew point close to air temperature promotes condensation, raising moisture and thereby lowering GCV. {MOISTURE_GCV_MECHANISM}",
         knowledge_type="established_principle", scientific_references=f"{REF_PSYCHROMETRY}",
         confidence_level="medium", confidence_rationale="Mechanism is established but typically a smaller moisture contributor than rainfall, hence medium rather than high."),
    dict(variable_name="dew_point", target_metric="moisture", relationship_type="direct",
         influence_direction="positive", influence_strength="medium",
         expected_lag_days_min=0, expected_lag_days_max=1,
         lag_description="Condensation effect is typically realised overnight into the following morning.",
         rationale="When dew point approaches surface temperature, condensation deposits moisture directly onto exposed coal, independent of rainfall.",
         knowledge_type="established_principle", scientific_references=f"{REF_PSYCHROMETRY}",
         confidence_level="medium", confidence_rationale="Established physics; magnitude is typically smaller than direct rainfall, justifying medium confidence."),
    dict(variable_name="dew_point", target_metric="ash", relationship_type="indirect",
         influence_direction="context_dependent", influence_strength="low",
         expected_lag_days_min=0, expected_lag_days_max=0,
         lag_description="No established mechanism/lag.",
         rationale="No established mechanism links dew point to mineral-matter content of coal.",
         knowledge_type="operational_assumption", scientific_references=None,
         confidence_level="low", confidence_rationale="Speculative; included for completeness pending statistical testing."),

    dict(variable_name="wind_speed", target_metric="gcv", relationship_type="indirect",
         influence_direction="context_dependent", influence_strength="medium",
         expected_lag_days_min=0, expected_lag_days_max=2,
         lag_description="Drying contribution accumulates over 0-2 days, contingent on simultaneous humidity.",
         rationale=f"Wind accelerates evaporative drying (lowering moisture, raising GCV) when humidity is low, but has little effect when humidity is high. {MOISTURE_GCV_MECHANISM}",
         knowledge_type="established_principle", scientific_references=f"{REF_PENMAN}",
         confidence_level="medium", confidence_rationale="Mechanism established but explicitly conditional on humidity, so effect on GCV alone is context-dependent."),
    dict(variable_name="wind_speed", target_metric="moisture", relationship_type="direct",
         influence_direction="negative", influence_strength="medium",
         expected_lag_days_min=0, expected_lag_days_max=1,
         lag_description="Boundary-layer renewal effect is largely same-day.",
         rationale="Wind speed may accelerate drying depending on humidity, by continuously replacing saturated boundary-layer air at the coal surface with drier air.",
         knowledge_type="established_principle", scientific_references=f"{REF_PENMAN}; {REF_PSYCHROMETRY}",
         confidence_level="medium", confidence_rationale="Well-established boundary-layer mechanism, but magnitude is explicitly humidity-dependent."),
    dict(variable_name="wind_speed", target_metric="ash", relationship_type="indirect",
         influence_direction="context_dependent", influence_strength="low",
         expected_lag_days_min=0, expected_lag_days_max=0,
         lag_description="If any effect exists, it would be via wind erosion of fines, immediate.",
         rationale="Strong sustained wind could in principle preferentially remove fine particulate from exposed stockpile surfaces, marginally shifting sampled ash, but this is a weak, unproven secondary mechanism.",
         knowledge_type="operational_assumption", scientific_references=None,
         confidence_level="low", confidence_rationale="Plausible but undocumented mechanism; flagged for statistical testing."),

    dict(variable_name="wind_gust", target_metric="gcv", relationship_type="indirect",
         influence_direction="context_dependent", influence_strength="low",
         expected_lag_days_min=0, expected_lag_days_max=0,
         lag_description="Transient, same-day only; unlikely to have multi-day carry-over.",
         rationale="Gusts may marginally add to the drying effect of sustained wind, but their brief duration limits cumulative contribution to moisture/GCV outcomes.",
         knowledge_type="operational_assumption", scientific_references=None,
         confidence_level="low", confidence_rationale="Secondary to sustained wind speed; incremental effect size not well quantified."),
    dict(variable_name="wind_gust", target_metric="moisture", relationship_type="indirect",
         influence_direction="context_dependent", influence_strength="low",
         expected_lag_days_min=0, expected_lag_days_max=0,
         lag_description="Transient, same-day only.",
         rationale="Gust-driven drying is plausible but transient compared to sustained wind speed's effect on moisture.",
         knowledge_type="operational_assumption", scientific_references=None,
         confidence_level="low", confidence_rationale="Plausible but weak/transient mechanism relative to sustained wind."),
    dict(variable_name="wind_gust", target_metric="ash", relationship_type="indirect",
         influence_direction="context_dependent", influence_strength="low",
         expected_lag_days_min=0, expected_lag_days_max=0,
         lag_description="If any effect exists, it would be immediate (fines entrainment during the gust).",
         rationale="Gusts could transiently entrain fine particulates, marginally affecting sampled ash, but this is speculative and undocumented.",
         knowledge_type="operational_assumption", scientific_references=None,
         confidence_level="low", confidence_rationale="Speculative secondary mechanism; included for completeness."),

    dict(variable_name="surface_pressure", target_metric="gcv", relationship_type="indirect",
         influence_direction="context_dependent", influence_strength="low",
         expected_lag_days_min=0, expected_lag_days_max=3,
         lag_description="Any effect would lag via pressure's association with incoming weather systems (e.g. falling pressure preceding rain), not pressure itself.",
         rationale="Surface pressure has no direct physical effect on coal moisture/quality; any relationship found would actually reflect pressure's role as a leading indicator of rainfall/humidity changes.",
         knowledge_type="operational_assumption", scientific_references=f"{REF_WMO_GLOSSARY}",
         confidence_level="low", confidence_rationale="No direct mechanism; any statistical association would be confounded by correlated weather variables."),
    dict(variable_name="surface_pressure", target_metric="moisture", relationship_type="indirect",
         influence_direction="context_dependent", influence_strength="low",
         expected_lag_days_min=0, expected_lag_days_max=3,
         lag_description="Lags via association with approaching frontal/monsoon systems.",
         rationale="Falling surface pressure is a standard precursor signal for precipitation systems; any moisture relationship is mediated through that association, not a direct mechanism.",
         knowledge_type="operational_assumption", scientific_references=f"{REF_WMO_GLOSSARY}",
         confidence_level="low", confidence_rationale="Indirect/confounded relationship; weak standalone predictive value expected."),
    dict(variable_name="surface_pressure", target_metric="ash", relationship_type="indirect",
         influence_direction="context_dependent", influence_strength="low",
         expected_lag_days_min=0, expected_lag_days_max=0,
         lag_description="No established mechanism/lag.",
         rationale="No established mechanism links surface pressure to coal mineral-matter content.",
         knowledge_type="operational_assumption", scientific_references=None,
         confidence_level="low", confidence_rationale="Included for completeness; expected null relationship."),

    dict(variable_name="cloud_cover", target_metric="gcv", relationship_type="indirect",
         influence_direction="negative", influence_strength="medium",
         expected_lag_days_min=0, expected_lag_days_max=2,
         lag_description="Acts via suppressed solar drying; builds over 0-2 days of sustained cloud cover.",
         rationale=f"Cloud cover reduces incoming solar radiation, suppressing evaporative drying, raising moisture and thereby lowering GCV. {MOISTURE_GCV_MECHANISM}",
         knowledge_type="established_principle", scientific_references=f"{REF_PENMAN}",
         confidence_level="medium", confidence_rationale="Mechanism well established; GCV link is indirect via moisture and solar radiation."),
    dict(variable_name="cloud_cover", target_metric="moisture", relationship_type="indirect",
         influence_direction="positive", influence_strength="medium",
         expected_lag_days_min=0, expected_lag_days_max=2,
         lag_description="Cloud cover may reduce natural drying over the period it persists, allowing moisture to be retained longer.",
         rationale="By attenuating solar radiation, persistent cloud cover suppresses the energy available for evaporation, indirectly supporting moisture retention.",
         knowledge_type="established_principle", scientific_references=f"{REF_PENMAN}",
         confidence_level="medium", confidence_rationale="Established radiative mechanism, but effect on moisture is mediated through solar radiation rather than direct."),
    dict(variable_name="cloud_cover", target_metric="ash", relationship_type="indirect",
         influence_direction="context_dependent", influence_strength="low",
         expected_lag_days_min=0, expected_lag_days_max=0,
         lag_description="No established mechanism/lag.",
         rationale="No established mechanism links cloud cover to mineral-matter content of coal.",
         knowledge_type="operational_assumption", scientific_references=None,
         confidence_level="low", confidence_rationale="Included for completeness; expected null relationship."),

    dict(variable_name="visibility", target_metric="gcv", relationship_type="indirect",
         influence_direction="context_dependent", influence_strength="low",
         expected_lag_days_min=0, expected_lag_days_max=1,
         lag_description="If any effect exists, it would track whichever underlying cause (fog/rain/dust) reduced visibility.",
         rationale="Visibility is an ambiguous composite proxy (fog, rain, or dust can each reduce it); any GCV relationship would actually be attributable to the specific underlying cause rather than visibility itself.",
         knowledge_type="operational_assumption", scientific_references=None,
         confidence_level="low", confidence_rationale="Ambiguous, multi-cause signal; weak standalone explanatory value expected."),
    dict(variable_name="visibility", target_metric="moisture", relationship_type="indirect",
         influence_direction="context_dependent", influence_strength="low",
         expected_lag_days_min=0, expected_lag_days_max=1,
         lag_description="Tracks whichever underlying moisture-related cause (fog/rain) reduced visibility, if any.",
         rationale="Reduced visibility from fog/mist indicates near-saturated air consistent with elevated moisture risk, but reduced visibility from dust/haze does not -- the relationship is conditional on cause.",
         knowledge_type="operational_assumption", scientific_references=None,
         confidence_level="low", confidence_rationale="Conditional/ambiguous relationship; requires disambiguation from other variables before any conclusion."),
    dict(variable_name="visibility", target_metric="ash", relationship_type="indirect",
         influence_direction="context_dependent", influence_strength="low",
         expected_lag_days_min=0, expected_lag_days_max=0,
         lag_description="No established mechanism/lag.",
         rationale="No established mechanism links atmospheric visibility to coal mineral-matter content.",
         knowledge_type="operational_assumption", scientific_references=None,
         confidence_level="low", confidence_rationale="Included for completeness; expected null relationship."),

    dict(variable_name="solar_radiation", target_metric="gcv", relationship_type="indirect",
         influence_direction="positive", influence_strength="high",
         expected_lag_days_min=0, expected_lag_days_max=2,
         lag_description="Drying benefit accumulates over 0-2 days of sustained solar input.",
         rationale=f"Solar radiation supplies the energy for evaporative drying, lowering moisture and raising as-received GCV. {MOISTURE_GCV_MECHANISM}",
         knowledge_type="established_principle", scientific_references=f"{REF_PENMAN}",
         confidence_level="high", confidence_rationale="Solar radiation as the primary evaporation energy source is foundational, well-established evapotranspiration theory."),
    dict(variable_name="solar_radiation", target_metric="moisture", relationship_type="direct",
         influence_direction="negative", influence_strength="high",
         expected_lag_days_min=0, expected_lag_days_max=1,
         lag_description="Largely same-day effect, with some carry-over if radiation is sustained over multiple days.",
         rationale="Increased solar radiation promotes drying by directly supplying the energy that drives evaporation at the coal surface.",
         knowledge_type="established_principle", scientific_references=f"{REF_PENMAN}",
         confidence_level="high", confidence_rationale="Foundational, well-established physical mechanism with minimal ambiguity."),
    dict(variable_name="solar_radiation", target_metric="ash", relationship_type="indirect",
         influence_direction="context_dependent", influence_strength="low",
         expected_lag_days_min=0, expected_lag_days_max=0,
         lag_description="No established mechanism/lag.",
         rationale="No established mechanism links solar radiation to coal mineral-matter content.",
         knowledge_type="operational_assumption", scientific_references=None,
         confidence_level="low", confidence_rationale="Included for completeness; expected null relationship."),

    dict(variable_name="thermal_stress", target_metric="gcv", relationship_type="indirect",
         influence_direction="negative", influence_strength="medium",
         expected_lag_days_min=0, expected_lag_days_max=2,
         lag_description="Builds over 0-2 days under sustained hot-humid conditions.",
         rationale="High thermal stress (hot + humid together) indicates conditions where the expected drying benefit of heat is undermined by humidity, tending to keep moisture elevated and GCV suppressed relative to what temperature alone would suggest.",
         knowledge_type="project_specific_rule", scientific_references=f"{REF_PSYCHROMETRY}",
         confidence_level="low", confidence_rationale="Underlying temperature-humidity interaction is real, but this composite index's specific predictive relationship with GCV is unproven and project-specific."),
    dict(variable_name="thermal_stress", target_metric="moisture", relationship_type="indirect",
         influence_direction="positive", influence_strength="medium",
         expected_lag_days_min=0, expected_lag_days_max=2,
         lag_description="Builds over 0-2 days under sustained hot-humid conditions.",
         rationale="High thermal stress signals conditions where humidity is suppressing the drying benefit of heat, favouring moisture retention.",
         knowledge_type="project_specific_rule", scientific_references=f"{REF_PSYCHROMETRY}",
         confidence_level="low", confidence_rationale="Composite index with a plausible mechanism but unvalidated specific formula/coefficients."),
    dict(variable_name="thermal_stress", target_metric="ash", relationship_type="indirect",
         influence_direction="context_dependent", influence_strength="low",
         expected_lag_days_min=0, expected_lag_days_max=0,
         lag_description="No established mechanism/lag.",
         rationale="No established mechanism links thermal stress to coal mineral-matter content.",
         knowledge_type="operational_assumption", scientific_references=None,
         confidence_level="low", confidence_rationale="Included for completeness; expected null relationship."),

    dict(variable_name="dew_spread", target_metric="gcv", relationship_type="indirect",
         influence_direction="negative", influence_strength="medium",
         expected_lag_days_min=0, expected_lag_days_max=1,
         lag_description="Condensation effect typically realised overnight; GCV impact follows within ~1 day.",
         rationale=f"A narrow dew spread signals elevated condensation risk, raising moisture and thereby lowering GCV. {MOISTURE_GCV_MECHANISM}",
         knowledge_type="established_principle", scientific_references=f"{REF_PSYCHROMETRY}",
         confidence_level="medium", confidence_rationale="Underlying condensation physics is well established; GCV link is indirect via moisture."),
    dict(variable_name="dew_spread", target_metric="moisture", relationship_type="direct",
         influence_direction="negative", influence_strength="medium",
         expected_lag_days_min=0, expected_lag_days_max=1,
         lag_description="A narrow dew spread (low value) corresponds to higher condensation risk overnight; direction is inverse (smaller dew_spread -> more moisture).",
         rationale="As dew spread narrows (air approaches saturation), condensation onto cool coal/stockpile surfaces becomes more likely, directly increasing surface moisture.",
         knowledge_type="established_principle", scientific_references=f"{REF_PSYCHROMETRY}",
         confidence_level="high", confidence_rationale="Direct, well-established psychrometric relationship between dew spread and condensation risk."),
    dict(variable_name="dew_spread", target_metric="ash", relationship_type="indirect",
         influence_direction="context_dependent", influence_strength="low",
         expected_lag_days_min=0, expected_lag_days_max=0,
         lag_description="No established mechanism/lag.",
         rationale="No established mechanism links dew spread to coal mineral-matter content.",
         knowledge_type="operational_assumption", scientific_references=None,
         confidence_level="low", confidence_rationale="Included for completeness; expected null relationship."),

    dict(variable_name="drying_potential", target_metric="gcv", relationship_type="indirect",
         influence_direction="positive", influence_strength="medium",
         expected_lag_days_min=0, expected_lag_days_max=2,
         lag_description="Builds over 0-2 days as favourable drying conditions persist.",
         rationale=f"High drying potential summarises conditions favourable to moisture reduction, which would raise as-received GCV. {MOISTURE_GCV_MECHANISM}",
         knowledge_type="project_specific_rule", scientific_references=f"{REF_PENMAN}",
         confidence_level="medium", confidence_rationale="Each underlying input is well-established; the composite's specific predictive strength for GCV is project-specific and pending validation."),
    dict(variable_name="drying_potential", target_metric="moisture", relationship_type="direct",
         influence_direction="negative", influence_strength="medium",
         expected_lag_days_min=0, expected_lag_days_max=2,
         lag_description="Builds over 0-2 days as favourable drying conditions persist.",
         rationale="By construction, this index combines variables that promote drying (temperature, wind, solar radiation) against those that retain moisture (humidity, rainfall), so it should track moisture inversely.",
         knowledge_type="project_specific_rule", scientific_references=f"{REF_PENMAN}",
         confidence_level="medium", confidence_rationale="Designed to track moisture by construction, but specific coefficients/weights are unvalidated against this platform's actual sampling outcomes."),
    dict(variable_name="drying_potential", target_metric="ash", relationship_type="indirect",
         influence_direction="context_dependent", influence_strength="low",
         expected_lag_days_min=0, expected_lag_days_max=0,
         lag_description="No established mechanism/lag.",
         rationale="No established mechanism links drying conditions to coal mineral-matter content.",
         knowledge_type="operational_assumption", scientific_references=None,
         confidence_level="low", confidence_rationale="Included for completeness; expected null relationship."),

    dict(variable_name="environmental_risk_index", target_metric="gcv", relationship_type="indirect",
         influence_direction="negative", influence_strength="low",
         expected_lag_days_min=0, expected_lag_days_max=3,
         lag_description="Builds over the trailing window the index incorporates (up to ~7 days via its rainfall component).",
         rationale="Higher composite environmental risk is intended to summarise adverse-for-quality conditions, which should associate with lower GCV via the moisture pathway, but this is an unvalidated project composite.",
         knowledge_type="project_specific_rule", scientific_references=None,
         confidence_level="low", confidence_rationale="Project-defined composite with no external literature equivalent; predictive validity must be established empirically."),
    dict(variable_name="environmental_risk_index", target_metric="moisture", relationship_type="indirect",
         influence_direction="positive", influence_strength="low",
         expected_lag_days_min=0, expected_lag_days_max=3,
         lag_description="Builds over the trailing window the index incorporates.",
         rationale="The index is constructed to rise under adverse, wetness-favouring conditions, so it should associate positively with moisture, but this is by design rather than independently demonstrated.",
         knowledge_type="project_specific_rule", scientific_references=None,
         confidence_level="low", confidence_rationale="Project-defined composite; validity pending Module 4 statistical testing."),
    dict(variable_name="environmental_risk_index", target_metric="ash", relationship_type="indirect",
         influence_direction="context_dependent", influence_strength="low",
         expected_lag_days_min=0, expected_lag_days_max=0,
         lag_description="No established mechanism/lag.",
         rationale="No established mechanism links this composite weather risk score to coal mineral-matter content.",
         knowledge_type="operational_assumption", scientific_references=None,
         confidence_level="low", confidence_rationale="Included for completeness; expected null relationship."),

    dict(variable_name="weather_stability_index", target_metric="gcv", relationship_type="indirect",
         influence_direction="context_dependent", influence_strength="low",
         expected_lag_days_min=0, expected_lag_days_max=7,
         lag_description="Reflects the trailing 7-day window used in its construction.",
         rationale="Stable weather is hypothesised to produce more consistent, representative sampling conditions; any GCV relationship would be about representativeness/variance rather than a direct mean shift.",
         knowledge_type="project_specific_rule", scientific_references=None,
         confidence_level="low", confidence_rationale="Plausible but unproven hypothesis about sampling representativeness rather than a direct quality driver."),
    dict(variable_name="weather_stability_index", target_metric="moisture", relationship_type="indirect",
         influence_direction="context_dependent", influence_strength="low",
         expected_lag_days_min=0, expected_lag_days_max=7,
         lag_description="Reflects the trailing 7-day window used in its construction.",
         rationale="Volatile weather may produce more variable moisture readings across a sampling period than stable weather, but this is a variance-related hypothesis, not a directional mean effect.",
         knowledge_type="project_specific_rule", scientific_references=None,
         confidence_level="low", confidence_rationale="Variance-related hypothesis, not a simple directional relationship; needs careful statistical framing in Module 4."),
    dict(variable_name="weather_stability_index", target_metric="ash", relationship_type="indirect",
         influence_direction="context_dependent", influence_strength="low",
         expected_lag_days_min=0, expected_lag_days_max=0,
         lag_description="No established mechanism/lag.",
         rationale="No established mechanism links weather stability to coal mineral-matter content.",
         knowledge_type="operational_assumption", scientific_references=None,
         confidence_level="low", confidence_rationale="Included for completeness; expected null relationship."),

    dict(variable_name="consecutive_wet_days", target_metric="gcv", relationship_type="indirect",
         influence_direction="negative", influence_strength="medium",
         expected_lag_days_min=1, expected_lag_days_max=4,
         lag_description="Effect strengthens with run length; 1-4 day lag typical before full moisture saturation impact on sampling.",
         rationale=f"Consecutive wet days may increase moisture accumulation cumulatively, which would lower as-received GCV. {MOISTURE_GCV_MECHANISM}",
         knowledge_type="operational_assumption", scientific_references=f"{REF_COAL_HANDBOOK}; {REF_CIMFR_WEATHERING}",
         confidence_level="medium", confidence_rationale="Cumulative wetting is a recognised operational concern; specific GCV lag/magnitude is context-dependent on stockpile geometry."),
    dict(variable_name="consecutive_wet_days", target_metric="moisture", relationship_type="direct",
         influence_direction="positive", influence_strength="high",
         expected_lag_days_min=1, expected_lag_days_max=4,
         lag_description="Moisture accumulates progressively with run length, typically saturating influence after 3-4 consecutive wet days.",
         rationale="Multi-day wet spells allow deeper, more thorough water penetration into stockpiled coal than an equivalent single-day total, directly raising accumulated moisture.",
         knowledge_type="operational_assumption", scientific_references=f"{REF_COAL_HANDBOOK}; {REF_CIMFR_WEATHERING}",
         confidence_level="medium", confidence_rationale="Strong operational consensus on cumulative wetting, though exact day-count thresholds vary by stockpile/coal type and are not universally quantified."),
    dict(variable_name="consecutive_wet_days", target_metric="ash", relationship_type="indirect",
         influence_direction="context_dependent", influence_strength="low",
         expected_lag_days_min=0, expected_lag_days_max=2,
         lag_description="If any effect exists, it would be via fines washing during extended wet spells.",
         rationale="Extended wet spells could in principle cause differential fines movement, marginally affecting sampled ash, but this is a weak, undocumented secondary mechanism.",
         knowledge_type="operational_assumption", scientific_references=None,
         confidence_level="low", confidence_rationale="Plausible but unproven; flagged for statistical testing."),

    dict(variable_name="consecutive_dry_days", target_metric="gcv", relationship_type="indirect",
         influence_direction="positive", influence_strength="medium",
         expected_lag_days_min=1, expected_lag_days_max=4,
         lag_description="Effect strengthens with run length, typically over 1-4 days.",
         rationale=f"Extended dry spells allow progressive surface drying, lowering moisture and raising as-received GCV. {MOISTURE_GCV_MECHANISM}",
         knowledge_type="operational_assumption", scientific_references=f"{REF_COAL_HANDBOOK}",
         confidence_level="medium", confidence_rationale="Cumulative drying is a reasonable operational heuristic; exact GCV gain per dry day is context-dependent."),
    dict(variable_name="consecutive_dry_days", target_metric="moisture", relationship_type="direct",
         influence_direction="negative", influence_strength="medium",
         expected_lag_days_min=1, expected_lag_days_max=4,
         lag_description="Moisture declines progressively with run length, with diminishing returns after several days.",
         rationale="Successive dry days allow cumulative surface and near-surface moisture loss, analogous to soil-moisture depletion under sustained dry conditions.",
         knowledge_type="operational_assumption", scientific_references=f"{REF_COAL_HANDBOOK}",
         confidence_level="medium", confidence_rationale="Reasonable, widely-assumed heuristic; precise quantitative effect is context-dependent (stockpile size/shape, coal rank)."),
    dict(variable_name="consecutive_dry_days", target_metric="ash", relationship_type="indirect",
         influence_direction="context_dependent", influence_strength="low",
         expected_lag_days_min=0, expected_lag_days_max=0,
         lag_description="No established mechanism/lag.",
         rationale="No established mechanism links dry-day run length to coal mineral-matter content.",
         knowledge_type="operational_assumption", scientific_references=None,
         confidence_level="low", confidence_rationale="Included for completeness; expected null relationship."),

    dict(variable_name="moisture_accumulation_index", target_metric="gcv", relationship_type="indirect",
         influence_direction="negative", influence_strength="medium",
         expected_lag_days_min=0, expected_lag_days_max=7,
         lag_description="Reflects the ~7-day half-life decay window built into the index.",
         rationale=f"This index is constructed to track accumulated moisture stress directly, so higher values should associate with lower GCV via the moisture pathway. {MOISTURE_GCV_MECHANISM}",
         knowledge_type="project_specific_rule", scientific_references=None,
         confidence_level="low", confidence_rationale="Designed by construction to track moisture, but the specific decay constant/weights are unvalidated against actual sampling outcomes."),
    dict(variable_name="moisture_accumulation_index", target_metric="moisture", relationship_type="direct",
         influence_direction="positive", influence_strength="medium",
         expected_lag_days_min=0, expected_lag_days_max=7,
         lag_description="Reflects the ~7-day half-life decay window built into the index.",
         rationale="The index is explicitly constructed as a decayed cumulative function of rainfall and humidity, intended to proxy accumulated moisture stress.",
         knowledge_type="project_specific_rule", scientific_references=f"{REF_HYDRO_API}",
         confidence_level="low", confidence_rationale="Conceptually grounded in known hydrological accounting approaches, but the specific decay constant is a project choice requiring empirical validation."),
    dict(variable_name="moisture_accumulation_index", target_metric="ash", relationship_type="indirect",
         influence_direction="context_dependent", influence_strength="low",
         expected_lag_days_min=0, expected_lag_days_max=0,
         lag_description="No established mechanism/lag.",
         rationale="No established mechanism links accumulated moisture stress to coal mineral-matter content.",
         knowledge_type="operational_assumption", scientific_references=None,
         confidence_level="low", confidence_rationale="Included for completeness; expected null relationship."),

    dict(variable_name="temperature_range", target_metric="gcv", relationship_type="indirect",
         influence_direction="positive", influence_strength="low",
         expected_lag_days_min=0, expected_lag_days_max=1,
         lag_description="Same-day proxy signal; weak/indirect, no strong lag expected.",
         rationale="A wide diurnal temperature range is associated with clear, dry conditions favourable to drying, which would tend to associate with higher GCV, but this is an indirect inferential proxy.",
         knowledge_type="operational_assumption", scientific_references=f"{REF_WMO_GLOSSARY}",
         confidence_level="low", confidence_rationale="Indirect proxy relationship, one inferential step removed from direct causation."),
    dict(variable_name="temperature_range", target_metric="moisture", relationship_type="indirect",
         influence_direction="negative", influence_strength="low",
         expected_lag_days_min=0, expected_lag_days_max=1,
         lag_description="Same-day proxy signal.",
         rationale="Wide diurnal range typically co-occurs with clear skies and low humidity, conditions generally unfavourable to moisture retention.",
         knowledge_type="operational_assumption", scientific_references=f"{REF_WMO_GLOSSARY}",
         confidence_level="low", confidence_rationale="Indirect proxy; should be read alongside humidity/cloud cover rather than standalone."),
    dict(variable_name="temperature_range", target_metric="ash", relationship_type="indirect",
         influence_direction="context_dependent", influence_strength="low",
         expected_lag_days_min=0, expected_lag_days_max=0,
         lag_description="No established mechanism/lag.",
         rationale="No established mechanism links diurnal temperature range to coal mineral-matter content.",
         knowledge_type="operational_assumption", scientific_references=None,
         confidence_level="low", confidence_rationale="Included for completeness; expected null relationship."),
]


def populate(db_path: str) -> int:
    con = sqlite3.connect(db_path)
    try:
        cur = con.cursor()
        cols = [
            "variable_name", "target_metric", "relationship_type", "influence_direction",
            "influence_strength", "expected_lag_days_min", "expected_lag_days_max",
            "lag_description", "rationale", "knowledge_type", "scientific_references",
            "confidence_level", "confidence_rationale", "requires_statistical_validation",
            "validation_status",
        ]
        sql = f"""
            INSERT INTO environmental_variable_influence ({",".join(cols)})
            VALUES ({",".join(["?"] * len(cols))})
            ON CONFLICT(variable_name, target_metric) DO UPDATE SET
                relationship_type=excluded.relationship_type,
                influence_direction=excluded.influence_direction,
                influence_strength=excluded.influence_strength,
                expected_lag_days_min=excluded.expected_lag_days_min,
                expected_lag_days_max=excluded.expected_lag_days_max,
                lag_description=excluded.lag_description,
                rationale=excluded.rationale,
                knowledge_type=excluded.knowledge_type,
                scientific_references=excluded.scientific_references,
                confidence_level=excluded.confidence_level,
                confidence_rationale=excluded.confidence_rationale,
                requires_statistical_validation=excluded.requires_statistical_validation,
                updated_at=datetime('now')
        """
        for row in ROWS:
            payload = {
                "variable_name": row["variable_name"],
                "target_metric": row["target_metric"],
                "relationship_type": row["relationship_type"],
                "influence_direction": row["influence_direction"],
                "influence_strength": row["influence_strength"],
                "expected_lag_days_min": row["expected_lag_days_min"],
                "expected_lag_days_max": row["expected_lag_days_max"],
                "lag_description": row["lag_description"],
                "rationale": row["rationale"],
                "knowledge_type": row["knowledge_type"],
                "scientific_references": row["scientific_references"],
                "confidence_level": row["confidence_level"],
                "confidence_rationale": row["confidence_rationale"],
                "requires_statistical_validation": 1,
                "validation_status": "pending",
            }
            cur.execute(sql, [payload[c] for c in cols])
        con.commit()
        return len(ROWS)
    finally:
        con.close()


if __name__ == "__main__":
    import sys
    db_file = sys.argv[1] if len(sys.argv) > 1 else "coal_eie.db"
    n = populate(db_file)
    print(f"Populated/updated {n} environmental_variable_influence rows in {db_file}")
